language: php
php:
  - 5.4
services: mongodb
env:
    global:
        - components=no
before_script:
    - travis_retry sudo apt-get install parallel
    - composer update satooshi/php-coveralls

install:
    - if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - composer self-update
    - composer install --no-interaction
    - npm install -g bower
    - bower cache-clean
    - bower install
    - mongo trackview --eval "printjson(db.dropDatabase())"
    - mongorestore src/Golovnya/TrackBundle/Resources/data/dump

script:
    - phpunit -c app/phpunit.xml.dist --coverage-clover app/logs/clover.xml --log-junit app/logs/junit.xml

after_script:
    - php bin/coveralls -v --exclude-no-stmt

addons:
    code_climate:
        repo_token: d02b8335d5f376fddb04c3e09794da6c8d704683af82f29e573bc182e9cef0e9
