imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

parameters:
    auth_required_channel: 'https'
    kernel.debug: false

# Assetic Configuration
assetic:
    node: /usr/local/bin/node
    filters:
        uglifycss:
            bin: /usr/local/bin/uglifycss
            apply_to: "\.css$"
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
            apply_to: "\.js$"

    assets:
        jasminejs:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/jasmine/lib/jasmine-core/jasmine.js'
            output: "js/jasmine.js"
        shiv_respond:
            inputs:
                - %kernel.root_dir%/../web/js/shiv_respond.js
            output: 'js/shiv_respond.js'
            filters:
                - uglifyjs2
 
        common:
            inputs:
                - %kernel.root_dir%/../web/js/main.js
            output: 'js/main.js'
            filters:
                - uglifyjs2
 
        main:
            inputs:
                - %kernel.root_dir%/../web/css/main.css

            output: 'css/main.css'
            filters:
                - uglifycss
