imports:
    - { resource: @GolovnyaTrackBundle/Resources/config/config.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


assetic:
    debug: %kernel.debug%
    use_controller: %kernel.debug%
    node: /usr/local/bin/node
    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs: ['@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/js/bootstrap.js']
            output: "js/bootstrap.js"
        bootstrap_css:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/css/bootstrap.css'
            output: "css/bootstrap.css"
            filters: [cssrewrite]

        bootstrap_map:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/css/bootstrap.css.map'
            output: "css/bootstrap.css.map"

        bootstrap_theme_map:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/css/bootstrap-theme.css.map'
            output: "css/bootstrap-theme.css.map"

        bootstrap_glyphicons_ttf:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf"

        bootstrap_glyphicons_eot:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"

        bootstrap_glyphicons_svg:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"

        bootstrap_glyphicons_woff:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: "Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff"

        bootstrap_glyphicons_woff2:
            inputs:
                - '@GolovnyaTrackBundle/Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2'
            output: "Resources/public/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2"

        jasminecss:
            inputs: ['@GolovnyaTrackBundle/Resources/public/vendor/jasmine/lib/jasmine-core/jasmine.css']
            output: "css/jasmine.css"
